import { Chess } from 'chess.js';
import { AI_SEARCH_SETTINGS, AI_DIFFICULTY_ORDER } from './aiConfig.js';
const VALUES = { p: 100, n: 320, b: 330, r: 500, q: 900, k: 0 };
export const SETTINGS = Object.freeze(Object.fromEntries(AI_DIFFICULTY_ORDER.map((name) => [name, Object.freeze({ depth: AI_SEARCH_SETTINGS[name].fallbackDepth, variety: AI_SEARCH_SETTINGS[name].multiPv })])));
const moveData = (move) => ({ from: move.from, to: move.to, promotion: move.promotion || 'q' });
const evaluation = (game, color) => { if (game.isCheckmate()) return game.turn() === color ? -100000 : 100000; if (game.isDraw()) return 0; let score = 0; for (const row of game.board()) for (const piece of row) if (piece) score += (piece.color === color ? 1 : -1) * VALUES[piece.type]; return score; };
const moves = (game) => game.moves({ verbose: true }).sort((a, b) => Number(Boolean(b.captured)) - Number(Boolean(a.captured)));
const search = (game, depth, alpha, beta, color) => { if (!depth || game.isGameOver()) return evaluation(game, color); const max = game.turn() === color; let best = max ? -Infinity : Infinity; for (const move of moves(game)) { game.move(moveData(move)); const value = search(game, depth - 1, alpha, beta, color); game.undo(); if (max) { best = Math.max(best, value); alpha = Math.max(alpha, value); } else { best = Math.min(best, value); beta = Math.min(beta, value); } if (beta <= alpha) break; } return best; };
export function chooseMove(fen, difficulty = 'Medium') { const game = new Chess(fen); const setting = SETTINGS[difficulty] || SETTINGS.Medium; const color = game.turn(); const scored = moves(game).map((move) => { game.move(moveData(move)); const score = search(game, setting.depth - 1, -Infinity, Infinity, color); game.undo(); return { move: moveData(move), score }; }).sort((a, b) => b.score - a.score); const candidates = scored.slice(0, Math.min(setting.variety, scored.length)); return candidates[Math.floor(Math.random() * candidates.length)]?.move || null; }
